### ISSUE TITLE
aws-toolbox\Get-ATEBInstanceLogs -EnvironmentName name

### ISSUE THREAD

**Issue by kehtabp** [fireflycons/aws-toolbox#18]
![image](https://user-images.githubusercontent.com/1008194/58950828-90bab280-8787-11e9-9d08-24c5fe1e6bac.png)

Text version:
```
aws-toolbox\Get-ATEBInstanceLogs -EnvironmentName css-exbox-prod
Getting EB environment details...
Checking instances for SSM...
Sending SSM command to i-0547c72cda6ebd86c, i-0fac48d87d29b2e65
Submitted command with ID c3bf2691-cafa-4f9f-86bd-8831cd11c1fd and waiting for status...
Collecting results from S3...
https://s3.eu-west-1.amazonaws.com/aws-toolbox-workspace-eu-west-1-612155760304/ssm-run-command/c3bf2691-cafa-4f9f-86bd
-8831cd11c1fd/i-0547c72cda6ebd86c/awsrunPowerShellScript/0.awsrunPowerShellScript/stdout: Not an S3 URL
At C:\Users\aleksandrovk\Documents\WindowsPowerShell\Modules\aws-toolbox\0.14.0\Private\S3\Split-S3Url.ps1:27 char:9
+         throw "$($S3Url): Not an S3 URL"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (https://s3.eu-w...: Not an S3 URL:String) [], RuntimeException
    + FullyQualifiedErrorId : https://s3.eu-west-1.amazonaws.com/aws-toolbox-workspace-eu-west-1-612155760304/ssm-run-
   command/c3bf2691-cafa-4f9f-86bd-8831cd11c1fd/i-0547c72cda6ebd86c/awsrunPowerShellScript/0.awsrunPowerShellScript/s
  tdout: Not an S3 URL
```

**Comment by fireflycons** [comment]
Interesting one @kehtabp 

If you have a look at https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/ in section `Old vs New` you'll see that 'regional endpoint' paths should be formed e.g. `s3-eu-west-1` with a `-` after the s3. This was clearly the case till when you last saw it work (me, yesterday).

Seems they've subtly changed it so it's now `s3.eu-west-1` and that's not referred to at all in that web page :-( 

So I'll fix it to look for all forms on that page, plus `s3.` and hopefully that'll future proof it.

**Comment by kehtabp** [comment]
wow, they must have literally changed it between 2 requests within 15
minutes
